### ISSUE TITLE
Setting hurt cause fires two entity damage events

### ISSUE THREAD

**Issue by BehrRiley** [DenizenScript/Denizen-For-Bukkit#1917] opened 2019-02-19 03:57 UTC
**Relevant Script:**
```
DamageListener: 
  type: world 
  debug: true 
  events: 
    on entity damages entity: 
      - narrate <context.cause>
    on entity dies:
      - narrate <context.cause>
```
**Relevant Debug:**
https://one.denizenscript.com/paste/52567
**/Version:**
git-Paper-524 (MC: 1.13.2)
**/Denizen Version** 
Denizen: 1.0.3-SNAPSHOT (build 625-DEV)

Casting Hurt on an entity will deal damage like normal, and will correctly assign the right **cause** if specified with the argument `(cause:<cause>)`, however will also create a second **cause** if you also specify `(source:<entity>)` to make the system treat that entity as the attacker. 
ie;
`- hurt 1 <target> cause:magic source:<player>`
will create two `<context.cause>`, one being the specified **cause**, the second being **entity_attack**.
if **cause** is specified as entity_attack, this will narrate entity_attack twice

Specifying the source entity is required to make the entity retaliate, to anger pigman correctly to the right target and to correctly assign a player as the damager in custom scripts where the**hurt** acts as the player dealing the damage

**Additional support as to why I think this should be a thing, relevant script:**
```
DamageListener: 
  type: world 
  debug: true 
  events: 
    on entity damages entity: 
      - if <context.damager> == <server.match_player[behr]||>: 
      - narrate <context.cause>
```
**relevant debug:**
https://one.denizenscript.com/paste/52568
there is no way for a player to create two `<context.cause>`'s with any form of damage to an entity, tested with punching, swiping with a sword, throwing magic potion/harming, shooting an arrow, throwing a trident, I ran out of ideas

additionally, this second debug shows on line 101 that if I execute this:
` /ex hurt 10 <player.target> cause:magic source:<player>`

the context will never return the specified **cause** if it kills the entity, it replaces it in this debug with **custom** and **fire_tick**

**Comment by mergu** [comment] 2019-02-19 04:38
Edited title to be more descriptive. Please try to be less verbose in your issue posts.

The hurt command will fire two damage events if you specify a cause - one for the cause, and another for what I assume is the actual damage. The second event will have a cause of `custom` if a source isn't set, or `entity_attack` if a source is set.

**Comment by mcmonkey4eva** [comment] 2019-02-19 09:30
This is a Bukkit API limitation - no way to cause damage with a cause and a source together.
The underlying NMS is not friendly towards that concept - it's based on a complex mess of custom type objects with weird differences and special cases.

We could technically make an NMS module helper to handle this stuff, but it'd be a lot of messy code where I'm not sure what benefit it actually brings.

The `cause` and `source` arguments are considered unstable and to be avoided when possible.

Also `debug: true` is redundant/pointless, `- if <context.damager> == <server.match_player[behr]||>:` is dumb in even the context of being a quick test.

I've committed some minor improvements to the hurt command that might track cause a bit better.

You can also now use `source_once` as an argument, which maaaay also improve things here.

**Closed as completed** 2019-02-19 09:30 UTC
