### ISSUE TITLE
Add "Seed:#" Argument to Createworld Command

### ISSUE THREAD

**Issue by Xenmai** [DenizenScript/Denizen-For-Bukkit#1510] opened 2016-12-16 15:49 UTC
^ Please? :D

**Comment by Morphan1** [comment] 2016-12-16 23:11
Added to the latest developmental builds

**Comment by AnthonyAMC** [comment] 2016-12-21 19:51
Why wasn't this marked as a dupe of #1412?

**Comment by Morphan1** [comment] 2016-12-21 20:16
Forgot. I'm going to go ahead and close both since it's in the developmental builds

**Closed by Morphan1** 2016-12-21 20:16 UTC
