### ISSUE TITLE
Can you add support for this please?

### ISSUE THREAD

**Issue by Devillion** [DenizenScript/Denizen-For-Bukkit#1346] opened 2016-03-17 21:46 UTC
Player.spigot().sendMessage(BaseComponent) method

Either it's not supported correctly or something, I get an error when I reload one of my custom plugins. It comes up with this: http://i.imgur.com/IArdxhL.png

**Comment by Morphan1** [comment] 2016-03-17 21:53
Are you using the [latest Denizen developmental build](http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/)? The line that error points to should never error unless you're not even using Spigot.

**Comment by Devillion** [comment] 2016-03-18 12:20
I updated to the latest spigot build before that error happened (I've ha spigot for the last 3 years) & I already had that denizen build on my server.

**Comment by mcmonkey4eva** [comment] 2016-03-18 12:24
That is this line: https://github.com/mcmonkey4eva/Denizen/blob/master/src/main/java/net/aufdemrand/denizen/utilities/packets/intercept/PacketOutHandler.java#L41
chat_message is the only thing that can NPE there... and it's just a pre-read Field reference.
IE, something that should never be null without a minimum of there being an error earlier than that.

Either you're not using latest builds somewhere, or there was another error earlier in your logs that is the true error source.

**Comment by GotoFinal** [comment] 2016-03-18 12:29
As author of this plugin in logs ;)

@mcmonkey4eva @Morphan1 
Nah... This is spigot, spigot DON'T use vanilla field for chat packets when using sendMessage(BaseComponent) method, as this will have bigger impact on performance, so it use own field and serialize it directly do buffer.

```
public class PacketPlayOutChat
  implements Packet<PacketListenerPlayOut>
{
  private IChatBaseComponent a;
  public BaseComponent[] components;
  private byte b;
```
So field "a" is null.

Hope that will help.

**Comment by Morphan1** [comment] 2016-03-18 20:25
@GotoFinal regardless of whether field "a" is null, the error appears to be saying that when sending the packet, field "a" **does not exist**. The only way that would be possible (that I can think of at the moment) is if:

1. Something is sending a custom packet that extends PacketPlayOutChat (which is stupid to do)
2. The Spigot brand (Paper or whatever else) being used decided to remove/rename that field entirely? or
3. Something big is going wrong with the way we're doing that reflection (doubtful but not impossible I guess)

If no error is happening far earlier than that NPE (for example, immediately when someone logs in) then the last 2 can pretty much be ruled out, I think.

**Comment by GotoFinal** [comment] 2016-03-19 01:00
@Morphan1 
Or he isn't using latest version of denizen:
https://github.com/mcmonkey4eva/Denizen/blob/70557ad0de5d1cd5d378727c4b17ccc76acc0422/src/main/java/net/aufdemrand/denizen/utilities/packets/intercept/PacketOutHandler.java#L41

So you have 2 options:
1. Believe in black magic that field disappeared for no reason or other weird stuff.
2. He have this version, and update will not fix this, as error is caused by null value of "a" field.

**Comment by Morphan1** [comment] 2016-03-19 02:37
@GotoFinal but that second option means that @Devillion lied and wasted both of our time :(

**Comment by Devillion** [comment] 2016-03-19 02:59
@Morphan1 I downloaded latest denizen directly from the link you posted

**Comment by Morphan1** [comment] 2016-03-19 04:31
This should be fixed in the latest development build.

**Comment by mcmonkey4eva** [comment] 2016-03-23 23:38
@Devillion can you confirm this fix?

**Closed** 2016-03-31 05:24 UTC
Labels: bug
