### ISSUE TITLE
Custom brewing recipes

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#2063] opened 2019-10-30 21:09 UTC
All is in the title :)

One of my big dreams in Denizen is to create custom brewing recipes in order to make awesome potions
So, it can be a special field in potions item scripts ?

**Comment by mcmonkey4eva** [comment] 2019-10-30 21:10
near perfect duplicate of #2046

**Closed as completed by mcmonkey4eva** 2019-10-30 21:10 UTC
Labels: duplicate

**Comment by MrMaleficus** [comment] 2019-11-06 17:00
Some elements that can be handy :

**BrewingStandRefueled** event:
_Triggers when a brewing stand block is about to refuel_
- Context : 
-- <context.item> returns the ItemTag of the item about to be used as fuel.
-- <context.power> returns the ElementTag(Number) of the fuel power of the item.
-- <context.consuming> returns the ElementTag(Boolean) of whether the item will be consumed.
-- <context.location> returns the LocationTag of the brewing stand.
- Determination
-- Element(Number) to set the new fuel power.
-- Element(Boolean) to set whether the item will be consumed.<InventoryTag.brewing_ingredient> and mechanism "InventoryTag.brewing_ingredient"

tag `<InventoryTag.brewing_ingredient>` & mec `brewing_ingredient`
- Returns the item being used as the brewing ingredient in this brewer inventory.
- Sets the brewing ingredient of this brewer inventory.

tag `<LocationTag.brewing_fuel_level>` & mec `brewing_fuel_level`
- Returns the fuel level of this brewing stand block.
- Sets the brewing fuel level of this brewing stand block.

tag `<InventoryTag.brewing_results>` & mec `brewing_results`
- Returns the list of items in the result slots in this brewer inventory.
- Sets the result slots in this brewer inventory.

tag `<InventoryTag.is_brewing_stand>`
- Returns `true` if the inventory is a brewing stand

Support for custom brewing recipes :

`custom_potion:
  type: item
  debug: false
  material: i@potion[flags=HIDE_POTION_EFFECTS]
  display name: "<&e>My little custom potion"
  recipes:
    1:
      type: shaped
      output_quantity: 1
      input:
      - i@air|i@iron_ingot|i@air
      - i@iron_ingot|i@glowstone_dust|i@iron_ingot
      - i@air|i@iron_ingot|i@air
    2:
      type: brewing
      input:
        base_potion: "i@ranom_potion"           // set the base potion need to brew, if none, set watter bottle as default
        ingredient: "i@custom_ingredient"              // mandatory field, set the ingredient needed to make the potion`
