### ISSUE TITLE
npc fishing and catching fish causes issues

### ISSUE THREAD

**Issue by calico-kid** [DenizenScript/Denizen-For-Bukkit#2004] opened 2019-08-19 06:14 UTC
version is 1.14.4 paper build 173
denizen version is Denizen-1.1.0-b4041-DEV
citizens version Citizens-2.0.25-b1743

when using the fish command from denizen in game and using /ex fish <player.selected_npc> <player.location> catch:fish 

the npc will start fishing but never reel the line back in then after a few seconds it will cast an additional line and then repeat  untill you have a bunch of lines in the water

![image](https://user-images.githubusercontent.com/5965970/63242921-cceda300-c20d-11e9-8b76-6c441afeaa70.png)
for refrence

**Comment by mcmonkey4eva** [comment] 2019-08-19 07:17
` and using /ex fish <player.selected_npc> <player.location> catch:fish`
Two things:
One, `<npc>` is all you need in `/ex`, as it automatically links the selected NPC.
Two: the fish command does not take an NPC as input, it uses the linked NPC, so you don't need that arg here all for this comand.

Also: Issue was caused by an error in NMS code, fixed via https://github.com/DenizenScript/Denizen/commit/ed69dcba4f4a030acf448916f45ecca98def02fe

**Closed as completed by mcmonkey4eva** 2019-08-19 07:17 UTC
