### ISSUE TITLE
Custom potions not working

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1181] opened 2015-10-05 13:33 UTC
I want to create an **apple juice** which regenerates two food levels.
Using the command `/give @p potion 1 8197 {CustomPotionEffects:[{Id:23,Amplifier:0,Duration:600}],display:{Name:"Saturation Potion"}}` I get what I want.
I used a healing potion as "base" because of the red :red_circle: color.
![2015-10-05_15 20 59](https://cloud.githubusercontent.com/assets/8706734/10281572/ab6b1976-6b75-11e5-9735-52e08f9d5d60.png)
If I now type `/ex give <player.item_in_hand>` I get a **normal instant healing potion**.
![2015-10-05_15 24 20](https://cloud.githubusercontent.com/assets/8706734/10281592/d55f094a-6b75-11e5-86f8-7e4309ed1a10.png)
Doing `/ex narrate <player.item_in_hand>` returns `i@potion,8197[display_name=Apple Juice;potion=INSTANT_HEAL,1,false,false]`. Replacing `INSTANT_HEAL` with `SATURATION` and then giving it to me also gives me **the wrong item**.

Please fix this bug! :smile:

**Comment by Talamar1** [comment] 2015-10-05 13:38
try using /ex give <player.item_in_hand.full>

**Comment by brainscript** [comment] 2015-10-05 13:44
@Talamar1 Doesn't fix this ...

**Comment by Morphan1** [comment] 2015-10-05 19:34
@mcmonkey4eva Probably related to #1078

**Comment by mcmonkey4eva** [comment] 2015-10-15 01:09
Er... yup, duplicate of 1078. Please show your support there to help move it up on our priority list!

**Closed by mcmonkey4eva** 2015-10-15 01:09 UTC
