### ISSUE TITLE
Mechanism "show_book" not opening unsigned books

### ISSUE THREAD

**Issue by Berufeng** [DenizenScript/Denizen-For-Bukkit#2139] opened 2020-02-02 01:17 UTC
The output of `/version` on my server is: 

> [17:15:36 INFO]: This server is running Paper version git-Paper-88 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[17:15:36 INFO]: Checking version, please wait...
[17:15:37 INFO]: Previous version: git-Paper-87 (MC: 1.15.2)
[17:15:37 INFO]: You are running the latest version

NOTE: I ran my debug originally on git-Paper-87, but I was able to reproduce the error after updating.

The output of `/version denizen` on my server is:

> [17:17:16 INFO]: Denizen version 1.1.2-SNAPSHOT (build 4576-DEV)
[17:17:16 INFO]: Author: The DenizenScript Team

Here's the debug:
> https://one.denizenscript.com/paste/64823

Here's the book script it's calling:
> https://one.denizenscript.com/haste/64824

The issue is:

When I do `/ex adjust <player> show_book:MyBook` on a book script set to `signed: true` it functions. When I do the same command on a book script set to `signed: false`, no errors are thrown, but no book pops up at all.

**Comment by mcmonkey4eva** [comment] 2020-02-02 08:47
Duplicate of https://github.com/DenizenScript/Denizen/issues/1943

**Closed as completed by mcmonkey4eva** 2020-02-02 08:47 UTC
