### ISSUE TITLE
Server Crash Error

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1242] opened 2015-11-22 09:39 UTC
Anony knowns what this is? I ran a script that got a list of like ~100 Chunks in it while this happend

http://mcmonkey.org/paste/22927

**Comment by mcmonkey4eva** [comment] 2015-11-22 09:41
@Morphan1

**Comment by Morphan1** [comment] 2015-11-22 19:09
Are you doing it all async? That could be a problem

**Comment by GomaTerzu** [comment] 2015-11-23 08:08
What am I doing async? D:

**Comment by Morphan1** [comment] 2015-11-23 21:42
I don't know, you haven't shown your script

**Comment by GomaTerzu** [comment] 2015-11-24 10:32
Because I have no idea what script might cause this or even if a script causes this at all.

My first guess would be this script from BlackCoyote: http://mcmonkey.org/denizen/repo/entry/58

**Comment by GomaTerzu** [comment] 2015-11-25 06:48
I stopped using the "unique ping" counter in BlackCoyotes script and had no crash in 3 days now. I am using a bungeecord setting and the "on server ping" won't work with that. Maybe this caused the errors. You can close this if you have no clue if you can find a fix or not.

**Comment by mcmonkey4eva** [comment] 2015-11-26 08:51
Closing as a duplicate of https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1243

**Closed by mcmonkey4eva** 2015-11-26 08:51 UTC
